In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/2022-ml-midterm-p1/submit.csv
/kaggle/input/2022-ml-midterm-p1/train.csv
/kaggle/input/2022-ml-midterm-p1/test.csv

In [2]:
train = pd.read_csv('/kaggle/input/2022-ml-midterm-p1/train.csv')
test = pd.read_csv('/kaggle/input/2022-ml-midterm-p1/test.csv')

In [3]:
train

,index,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,0,63,1,1,145,233,1,2,150,0,2.3,3,0,6,0
1,1,67,1,4,160,286,0,2,108,1,1.5,2,3,3,2
2,2,67,1,4,120,229,0,2,129,1,2.6,2,2,7,1
3,4,41,0,2,130,204,0,2,172,0,1.4,1,0,3,0
4,5,56,1,2,120,236,0,0,178,0,0.8,1,0,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237,295,41,1,2,120,157,0,0,182,0,0.0,1,0,3,0
238,296,59,1,4,164,176,1,2,90,0,1.0,2,2,6,3
239,299,68,1,4,144,193,1,0,141,0,3.4,2,2,7,2
240,300,57,1,4,130,131,0,0,115,1,1.2,2,1,7,3
241,301,57,0,2,130,236,0,2,174,0,0.0,2,1,3,1

In [4]:
test

,index,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,3,37,1,3,130,250,0,0,187,0,3.5,3,0,3
1,6,62,0,4,140,268,0,2,160,0,3.6,3,2,3
2,21,58,0,1,150,283,1,2,162,0,1.0,1,0,3
3,24,60,1,4,130,206,0,2,132,1,2.4,2,2,7
4,31,60,1,4,117,230,1,0,160,1,1.4,1,2,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,293,63,1,4,140,187,0,2,144,1,4.0,1,2,7
57,294,63,0,4,124,197,0,0,136,1,0.0,2,0,3
58,297,57,0,4,140,241,0,0,123,1,0.2,2,0,7
59,298,45,1,1,110,264,0,0,132,0,1.2,2,0,7
60,302,38,1,3,138,175,0,0,173,0,0.0,1,-1,3

In [5]:
y_train = train['target']
x_train = train.drop(['target'],axis=1)
x_test = test

In [6]:
y_train[y_train>0] = 1

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [7]:
from sklearn.linear_model import LogisticRegression

log = LogisticRegression(solver='saga', max_iter=10000)
log.fit(x_train,y_train)
y_pred = log.predict(x_test)

In [8]:
submit = pd.read_csv('/kaggle/input/2022-ml-midterm-p1/submit.csv')
submit['target']= y_pred
submit.to_csv('submit.csv',index =False)